name: Deploy Staging (Production Ready)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  NODE_VERSION: 22
  APP_NAME: csw-live
  RESOURCE_GROUP: cswapp-rg

jobs:
  quality-check:
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Validate backend URL secret
        run: |
          if [ -z "$VITE_BACKEND_URL" ]; then
            echo "Missing secret VITE_BACKEND_URL."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: quality-check
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
    environment:
      name: production
      url: https://${{ env.APP_NAME }}.azurewebsites.net

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC / Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure backend URL app setting
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.APP_NAME }}
          app-settings-json: |
            [
              {
                "name": "VITE_BACKEND_URL",
                "value": "${{ secrets.VITE_BACKEND_URL }}"
              }
            ]

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Azure Web App (Production)
        run: |
          az webapp deploy \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME }} \
            --src-path ./dist

      - name: Output Live URL
        run: |
          echo "Deployed successfully to https://${{ env.APP_NAME }}.azurewebsites.net"
